### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by shreyansh26** [vopani/jaxton#1]
First of all, thanks for creating these.

And this is not a big issue at all, but since everything is so perfect, you would also probably want to fix the last cell of the "Jaxton: Pseudorandom Numbers (Solutions)" notebook.

It uses `key_5` and not `key_7` in the solution.

![image](https://user-images.githubusercontent.com/20071112/152986482-707c0e01-bd9e-4bbd-8886-4e91c9cc2d62.png)

**Comment by vopani** [comment]
@shreyansh26 Thanks for reporting this! I've updated it.
